#pragma once

namespace Hyve::Parser {

    enum class HAstOperatorType {
        ADD,
        SUBTRACT,
        MULTIPLY,
        DIVIDE,
        MODULO,
        EQUAL,
        NOT_EQUAL,
        GREATER_THAN,
        LESS_THAN,
        GREATER_THAN_OR_EQUAL,
        LESS_THAN_OR_EQUAL,
        AND,
        OR,
        XOR,
        NOT,
        BITWISE_AND,
        BITWISE_OR,
        BITWISE_XOR,
        BITWISE_NOT,
        BITWISE_LEFT_SHIFT,
        BITWISE_RIGHT_SHIFT,
        ASSIGN,
        ADD_ASSIGN,
        SUBTRACT_ASSIGN,
        MULTIPLY_ASSIGN,
        DIVIDE_ASSIGN,
        MODULO_ASSIGN,
        AND_ASSIGN,
        OR_ASSIGN,
        XOR_ASSIGN,
        BITWISE_AND_ASSIGN,
        BITWISE_OR_ASSIGN,
        BITWISE_XOR_ASSIGN,
        BITWISE_LEFT_SHIFT_ASSIGN,
        BITWISE_RIGHT_SHIFT_ASSIGN,
        INCREMENT,
        DECREMENT,
        INVALID_OPERATOR
    };
}