name: Ubuntu - Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Buildchain
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 19
          sudo apt-get install -y clang-19
          sudo apt-get install -y llvm-19-dev
          sudo apt-get install -y libstdc++-11-dev
          sudo apt-get install libc++-dev libc++abi-dev
      - name: Build Hyve
        run: |
          export CC=clang-19
          export CXX=clang++-19
          cmake -G Ninja -B build -S ./ -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/lib/llvm-19/cmake
          ninja -C build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hyve-release-deploy
          path: build/hyvec/hyvec