name: Release - Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Buildchain
        run: |
          sudo apt-get update
          sudo apt install -y clang
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh all

      - name: Build Hyve
        run: |
          export CC=clang
          export CXX=clang++
          cmake -G Ninja -B build -S ./ -DCMAKE_BUILD_TYPE=Release
          ninja -C build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: hyve-release-deploy
          path: build
