name: Release - Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker Build
        run: docker build -t hyve -f Dockerfile .
      - name: Docker Run
        run: |
          docker run -v ${{ github.workspace }}:/project \
            -v ${{ github.workspace }}/build-output:/deploy \
            hyve

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: hyve-release-deploy
          path: build-output
