name: Release - Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Get LLVM
        run: git clone https://github.com/llvm/llvm-project --depth 1 --branch main llvm-project
      - name: Make LLVM Project
        run: |
          cd llvm-project
          cmake -G Ninja -S ./llvm -B build -DLLVM_TARGETS_TO_BUILD="X86;ARM;AArch64" -DLLVM_ENABLE_PROJECTS="llvm;lldb;clang;clang-tools-extra;bolt" -DCMAKE_BUILD_TYPE=Release -Thost=x64
      - name: Build LLVM Project
        run: ninja -C build
      - name: Build Hyve
        run: |
          cd ..
          cmake -G "Visual Studio 17 2022" -B build -S ./ -DCMAKE_PREFIX_PATH="./llvm-project/build/lib/cmake/llvm" -DCMAKE_BUILD_TYPE=Release
          ninja -C build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: hyve-release-deploy
          path: build
